# Generated by Django 5.1.15 on 2026-10-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_add_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='_categories_text',
            field=models.CharField(blank=True, help_text='Comma-separated categories (legacy)', max_length=500),
        ),
    ]
