# Generated by Django 5.1.15 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_copyhistory_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='copy_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]