# Generated by Django 5.1.15 on 2026-06-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_copy_id_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='donor',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
