# Generated by Django 5.1.15 on 2026-06-03 01:39

from django.db import migrations, models


def backfill_loan_ids(apps, schema_editor):
    Loan = apps.get_model("loans", "Loan")
    for loan in Loan.objects.all():
        loan.loan_id = f"{loan.checkout_date:%Y%m%d}-{loan.user.lrn}-{loan.book_copy.copy_id}"
        loan.save(update_fields=["loan_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="loan_id",
            field=models.CharField(max_length=200, unique=False, blank=True),
        ),
        migrations.RunPython(backfill_loan_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="loan",
            name="loan_id",
            field=models.CharField(max_length=200, unique=True, blank=True),
        ),
    ]