# Generated by Django 5.1.15 on 2026-06-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_wall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freedompost',
            name='is_anonymous',
        ),
    ]
